from DeepClassifier.components.data_ingestion import DataIngestion
from DeepClassifier.components.prepare_base_model import PrepareBaseModel
from DeepClassifier.components.prepare_callbacks import PrepareCallbacks
from DeepClassifier.components.model_training import ModelTraining
from DeepClassifier.components.model_evaluation import ModelEvaluation