root_artifact_dir: artifacts

data_ingestion:
  artifact_dir: artifacts/data_ingestion
  source_download_url: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  downloaded_data_file_path: artifacts/data_ingestion/data.zip
  unzipped_data_dir: artifacts/data_ingestion

prepare_base_model:
  artifact_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  artifact_dir: artifacts/prepare_callbacks
  tensorboard_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoints/model.h5

model_training:
  artifact_dir: artifacts/model_training
  trained_model_filepath: artifacts/model_training/model.h5

model_evaluation:
  scores_filepath: scores.json
  trained_model_filepath: artifacts/model_training/model.h5
  test_data_dir: artifacts/data_ingestion
  remote_server_uri: https://dagshub.com/TewariUtkarsh/Deep_CNN_Classifier.mlflow
  train_params: 
    epochs: 1